//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Five_P.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FivePEntities : DbContext
    {
        public FivePEntities()
            : base("name=FivePEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Friend> Friends { get; set; }
        public virtual DbSet<Like> Likes { get; set; }
        public virtual DbSet<Like_Reply_Post> Like_Reply_Post { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Rate_Post> Rate_Post { get; set; }
        public virtual DbSet<Rate_Reply_Post> Rate_Reply_Post { get; set; }
        public virtual DbSet<Reply_Post> Reply_Post { get; set; }
        public virtual DbSet<Reviews_User> Reviews_User { get; set; }
        public virtual DbSet<Search> Searches { get; set; }
        public virtual DbSet<Show_Activate_Post> Show_Activate_Post { get; set; }
        public virtual DbSet<Show_Activate_Reply_Post> Show_Activate_Reply_Post { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<Technology> Technologies { get; set; }
        public virtual DbSet<Technology_Care> Technology_Care { get; set; }
        public virtual DbSet<Technology_Post> Technology_Post { get; set; }
        public virtual DbSet<Tick_Post> Tick_Post { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
