//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Five_P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews_User
    {
        public int reviews_user_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> reviews_id_user { get; set; }
        public Nullable<bool> Review { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
