//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Five_P.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Show_Activate_Post
    {
        public int show_activate_post_id { get; set; }
        public Nullable<int> post_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> show_activate_post_datetime { get; set; }
        public Nullable<bool> show_activate_post_Readed { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
